### ISSUE TITLE
Mitörtént :c

### ISSUE THREAD

**Issue by szerimartin** [matyas94/Rajongoi9A-D#48]
![image](https://github.com/matyas94/Rajongoi9A-D/assets/158025917/b755c874-77b8-4b25-a675-f69b8b41bbdc)

**Comment by OlahBalazs1** [comment]
ez melyik branch? a main működik nekem
egyébként meg úgy tűnik, hogy nem találja CSS fájlt
a linkben írd át a "css/"-t  "/css/"-re
